User auth
Moyseos/insta pull request #5
Opened 2017-07-05 16:09 UTC by Moyseos

i have added the user authentication, and the bcrypt for safer password, 
you can test that by creating a user and trying to signup.

2017-07-06 01:04 UTC, dtofuah commented
dude i don't know if you just copied and paste the auth code because we don't have a renderTamplate function in our code. You were also redirecting to a /home and we dont have anything like that.  I dont understand what you did. Its not working and in your sigup its not saving the username and first and last name in the database only the password. You lost me on here, please fix it

2017-07-06 23:43 UTC, wbobeirne commented
Hey Donald, I'm seeing that he added the renderTemplate function to util/renderTemplate.js in this branch, so that's a part of the pull request.

However, I do see some issues in here, so I'll drop a review in to try and help. But try to do the same as well, it helps if you can drop notes exactly where you see issues in code.

2017-07-06 23:47 UTC, wbobeirne requested changes

2017-07-06 23:47 UTC, wbobeirne commented on router/signup.js
> +	renderTemplate(res, "Login", "login");
It looks like the "/signup" route is rendering the "login" page here, it should probably render "signup".

2017-07-06 23:47 UTC, wbobeirne commented on views/pages/login.ejs
> +<html>
Pages shouldn't be full `<html>` pages, they should just have the content that's specific to an individual page. You should move the boilerplate into your `views/template.ejs`

2017-07-06 23:47 UTC, wbobeirne commented on app.js
> +					res.redirect("/home");
It looks like you don't have a `/home` route yet, so you probably don't want to redirect there.

2017-07-06 23:47 UTC, wbobeirne commented on app.js
> +		req.redirect("/home");
Same as the issue below, no `/home` route

2017-07-09 18:25 UTC, merged

2017-07-09 18:26 UTC, dtofuah commented
ok looks good